Webhooks = {
    ['band'] = 'WEBHOOK HERE',
    ['bodycam'] = 'WEBHOOK HERE',
    ['divingsuit'] = 'WEBHOOK HERE',
    ['evidence'] = 'WEBHOOK HERE',
    ['gps'] = 'WEBHOOK HERE',
    ['interactions'] = 'WEBHOOK HERE',
    ['jail'] = 'WEBHOOK HERE',
    ['mugshot'] = 'WEBHOOK HERE',
    ['objects'] = 'WEBHOOK HERE',
    ['sounds'] = 'WEBHOOK HERE',
    ['speedcam'] = 'WEBHOOK HERE',
    ['trunks'] = 'WEBHOOK HERE',
    ['tickets'] = 'WEBHOOK HERE',
}