INSERT INTO `items` (`name`, `label`, `weight`) VALUES
	('ammonia', 'Ammonia', 500),
	('sodium_benzoate', 'Sodium benzoate', 750),
	('meth_tray', 'Meth tray', 1000),
	('meth', 'Meth', 1),
	('meth_bag', 'Meth bag', 50),
	('plastic_bag', 'Plastic bag', 40),
	('meth_syringe', 'Meth syringe', 75),
	('coke_seed', 'Cocaine seed', 10),
	('coke_leaf', 'Cocaine leaf', 50),
	('coke_paste', 'Cocaine paste', 150),
	('coke', 'Cocaine', 1),
	('coke_bag', 'Cocaine bag', 50),
	('coke_brick', 'Cocaine brick', 200),
	('coke_doll', 'Cocaine doll', 500),
	('weed_seed', 'Weed seed', 5),
	('weed_pot', 'Flower Pot', 500),
	('trowel', 'Trowel', 150),
	('weed_bud', 'Weed bud', 25),
	('clean_weed_bud', 'Clean weed bud', 20),
	('cookie_dough', 'Cookie dough', 200),
	('weed_cookie', 'Weed cookie', 50),
	('weed_bag', 'Weed bag', 50),
	('weed_joint', 'Weed joint', 15),
	('weed_papers', 'Weed papers', 5),
	('poppy_seeds', 'Poppy seeds', 5),
	('poppy_plant', 'Poppy plant', 100),
	('opium', 'Opium', 1),
	('heroin', 'Heroin', 1),
	('heroin_bag', 'Heroin bag', 50),
	('heroin_syringe', 'Heroin syringe', 75),
	('syringe', 'Syringe', 25),
	('ergot_fungus', 'Ergot fungus', 50),
	('generic_leaf', 'Leaf', 20),
	('lsd_liquid', 'LSD liquid', 25),
	('lsd', 'LSD', 1),
	('art_papers', 'Art papers', 5),
	('safrole_oil', 'Safrole oil', 300),
	('ecstasy_crystals', 'Ecstasy crystals', 1),
	('ecstasy_pill', 'Ecstasy pill', 15),
	('mushrooms', 'Mushrooms', 1),
	('mushroom_powder', 'Mushroom powder', 1),
	('chocolate_chips', 'Chocolate chips', 30),
	('mushroom_chocolate', 'Mushroom chocolate', 45),
	('anesthetic', 'Anesthetic', 200),
	('ketamine', 'Ketamine', 1),
	('ketamine_bag', 'Ketamine bag', 50),
	('baking_soda', 'Baking soda', 100),
	('crack', 'Crack', 1),
	('crack_bag', 'Crack bag', 50),
	('crack_pipe', 'Crack pipe', 150),
	('crack_syringe', 'Crack syringe', 75),
	('pipe', 'Pipe', 100),
	('npp_chemical', 'NPP chemical', 300),
	('aniline_solution', 'Aniline solution', 250),
	('fentanyl', 'Fentanyl', 1),
	('fentanyl_bag', 'Fentanyl bag', 25),
	('meth_table', 'Meth table', 2250),
	('coke_table', 'Coke table', 2250),
	('weed_table', 'Weed table', 2250),
	('chem_table', 'Chemistry table', 2250),
	('burner_phone', 'Burner phone', 200),
	('light1', 'Portable Lamp', 2000),
	('light2', 'Portable Lamp', 2000),
	('fertilizer', 'Fertilizer', 250),
	('water_can', 'Watering can', 250)
;