
return {

    -- ═══════════════════════════════════════════
    -- DONOR  (niet te koop)
    -- ═══════════════════════════════════════════
    furiawb = {
        name     = 'Furia WB',
        brand    = 'Grotti',
        model    = 'furiawb',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `furiawb`,
    },
    buffalowb = {
        name     = 'Buffalo WB',
        brand    = 'Bravado',
        model    = 'buffalowb',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `buffalowb`,
    },
    italigton = {
        name     = 'Itali GTO N',
        brand    = 'Progen',
        model    = 'italigton',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `italigton`,
    },
    turismos = {
        name     = 'Turismo S',
        brand    = 'Grotti',
        model    = 'turismos',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `turismos`,
    },
    severo = {
        name     = 'Severo',
        brand    = 'Pegassi',
        model    = 'severo',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `severo`,
    },
    supergts = {
        name     = 'Super GTS',
        brand    = 'Enus',
        model    = 'supergts',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `supergts`,
    },
    cycloneex0 = {
        name     = 'Cyclone EX0',
        brand    = 'Coil',
        model    = 'cycloneex0',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `cycloneex0`,
    },
    h4rxst2 = {
        name     = 'H4Rx ST2',
        brand    = 'Karin',
        model    = 'h4rxst2',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `h4rxst2`,
    },
    hurricane = {
        name     = 'Hurricane',
        brand    = 'Pegassi',
        model    = 'hurricane',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `hurricane`,
    },
    neross = {
        name     = 'Nero S',
        brand    = 'Truffade',
        model    = 'neross',
        price    = 1,
        category = 'super',
        type     = 'automobile',
        hash     = `neross`,
    },

    -- ═══════════════════════════════════════════
    -- STARTER  (€18.000 – €95.000)
    -- Werkbakjes – bereikbaar met startgeld
    -- ═══════════════════════════════════════════
    issi8s = {
        name     = 'Issi 8 S',
        brand    = 'Weeny',
        model    = 'issi8s',
        price    = 18000,
        category = 'compacts',
        type     = 'automobile',
        hash     = `issi8s`,
    },
    odyssey = {
        name     = 'Odyssey',
        brand    = 'Zirconium',
        model    = 'odyssey',
        price    = 25000,
        category = 'compacts',
        type     = 'automobile',
        hash     = `odyssey`,
    },
    stanier93 = {
        name     = 'Stanier 93',
        brand    = 'Vapid',
        model    = 'stanier93',
        price    = 35000,
        category = 'compacts',
        type     = 'automobile',
        hash     = `stanier93`,
    },
    tulip4 = {
        name     = 'Tulip 4',
        brand    = 'Declasse',
        model    = 'tulip4',
        price    = 48000,
        category = 'compacts',
        type     = 'automobile',
        hash     = `tulip4`,
    },
    turtle = {
        name     = 'Turtle',
        brand    = 'Dinka',
        model    = 'turtle',
        price    = 68000,
        category = 'compacts',
        type     = 'automobile',
        hash     = `turtle`,
    },
    asterope2s = {
        name     = 'Asterope 2 S',
        brand    = 'Karin',
        model    = 'asterope2s',
        price    = 95000,
        category = 'compacts',
        type     = 'automobile',
        hash     = `asterope2s`,
    },

    -- ═══════════════════════════════════════════
    -- SLIDERS / SEDANS  (€130.000 – €320.000)
    -- ═══════════════════════════════════════════
    asteropers = {
        name     = 'Asteropers',
        brand    = 'Karin',
        model    = 'asteropers',
        price    = 130000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `asteropers`,
    },
    accolade = {
        name     = 'Accolade',
        brand    = 'Enus',
        model    = 'accolade',
        price    = 160000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `accolade`,
    },
    elegyrh7 = {
        name     = 'Elegy RH7',
        brand    = 'Annis',
        model    = 'elegyrh7',
        price    = 190000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `elegyrh7`,
    },
    torrence = {
        name     = 'Torrence',
        brand    = 'Declasse',
        model    = 'torrence',
        price    = 220000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `torrence`,
    },
    oracxsle = {
        name     = 'Orac X SLE',
        brand    = 'Übermacht',
        model    = 'oracxsle',
        price    = 255000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `oracxsle`,
    },
    ccadeesv = {
        name     = 'C Cade ESV',
        brand    = 'Albany',
        model    = 'ccadeesv',
        price    = 285000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `ccadeesv`,
    },
    primolx = {
        name     = 'Primo LX',
        brand    = 'Albany',
        model    = 'primolx',
        price    = 320000,
        category = 'sedans',
        type     = 'automobile',
        hash     = `primolx`,
    },

    -- ═══════════════════════════════════════════
    -- TRUCKS / OFFROAD  (€110.000 – €270.000)
    -- ═══════════════════════════════════════════
    rebelc2 = {
        name     = 'Rebel C2',
        brand    = 'Karin',
        model    = 'rebelc2',
        price    = 110000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `rebelc2`,
    },
    sandkingd = {
        name     = 'Sandking D',
        brand    = 'Vapid',
        model    = 'sandkingd',
        price    = 128000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `sandkingd`,
    },
    contenderc = {
        name     = 'Contender C',
        brand    = 'Vapid',
        model    = 'contenderc',
        price    = 145000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `contenderc`,
    },
    dubstab = {
        name     = 'Dubsta B',
        brand    = 'Benefactor',
        model    = 'dubstab',
        price    = 162000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `dubstab`,
    },
    ccadefxt = {
        name     = 'C Cade FXT',
        brand    = 'Albany',
        model    = 'ccadefxt',
        price    = 178000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `ccadefxt`,
    },
    rebelc = {
        name     = 'Rebel C',
        brand    = 'Karin',
        model    = 'rebelc',
        price    = 192000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `rebelc`,
    },
    nsandstorm = {
        name     = 'N Sandstorm',
        brand    = 'Vapid',
        model    = 'nsandstorm',
        price    = 205000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `nsandstorm`,
    },
    highmare = {
        name     = 'Highmare',
        brand    = 'Vapid',
        model    = 'highmare',
        price    = 218000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `highmare`,
    },
    caracara6x6 = {
        name     = 'Caracara 6x6',
        brand    = 'Vapid',
        model    = 'caracara6x6',
        price    = 232000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `caracara6x6`,
    },
    contenderbaja = {
        name     = 'Contender Baja',
        brand    = 'Vapid',
        model    = 'contenderbaja',
        price    = 245000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `contenderbaja`,
    },
    h4rxgranUT = {
        name     = 'H4Rx Gran UT',
        brand    = 'Karin',
        model    = 'h4rxgranUT',
        price    = 258000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `h4rxgranUT`,
    },
    patriots = {
        name     = 'Patriot S',
        brand    = 'Mammoth',
        model    = 'patriots',
        price    = 270000,
        category = 'offroad',
        type     = 'automobile',
        hash     = `patriots`,
    },

    -- ═══════════════════════════════════════════
    -- MOTORCYCLES  (€75.000 – €195.000)
    -- ═══════════════════════════════════════════
    frakas = {
        name     = 'Frakas',
        brand    = 'Western',
        model    = 'frakas',
        price    = 75000,
        category = 'motorcycles',
        type     = 'bike',
        hash     = `frakas`,
    },
    bati901 = {
        name     = 'Bati 901',
        brand    = 'Pegassi',
        model    = 'bati901',
        price    = 128000,
        category = 'motorcycles',
        type     = 'bike',
        hash     = `bati901`,
    },
    shinobir = {
        name     = 'Shinobi R',
        brand    = 'Nagasaki',
        model    = 'shinobir',
        price    = 195000,
        category = 'motorcycles',
        type     = 'bike',
        hash     = `shinobir`,
    },

    -- ═══════════════════════════════════════════
    -- SUV  (€150.000 – €360.000)
    -- ═══════════════════════════════════════════
    ncavalcade = {
        name     = 'N Cavalcade',
        brand    = 'Albany',
        model    = 'ncavalcade',
        price    = 150000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `ncavalcade`,
    },
    nriata = {
        name     = 'Nriata',
        brand    = 'Vapid',
        model    = 'nriata',
        price    = 178000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `nriata`,
    },
    toros2 = {
        name     = 'Toros 2',
        brand    = 'Pegassi',
        model    = 'toros2',
        price    = 210000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `toros2`,
    },
    peacemaker = {
        name     = 'Peacemaker',
        brand    = 'HVY',
        model    = 'peacemaker',
        price    = 242000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `peacemaker`,
    },
    space = {
        name     = 'Space',
        brand    = 'Canis',
        model    = 'space',
        price    = 272000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `space`,
    },
    dubsta22 = {
        name     = 'Dubsta 22',
        brand    = 'Benefactor',
        model    = 'dubsta22',
        price    = 310000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `dubsta22`,
    },
    astronc = {
        name     = 'Astron C',
        brand    = 'Pfister',
        model    = 'astronc',
        price    = 360000,
        category = 'suvs',
        type     = 'automobile',
        hash     = `astronc`,
    },

    -- ═══════════════════════════════════════════
    -- MUSCLE  (€185.000 – €545.000)
    -- ═══════════════════════════════════════════
    espexecutive = {
        name     = 'Esp Executive',
        brand    = 'Enus',
        model    = 'espexecutive',
        price    = 185000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `espexecutive`,
    },
    kawaii = {
        name     = 'Kawaii',
        brand    = 'Dinka',
        model    = 'kawaii',
        price    = 205000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `kawaii`,
    },
    stratumc = {
        name     = 'Stratum C',
        brand    = 'Zirconium',
        model    = 'stratumc',
        price    = 222000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `stratumc`,
    },
    coqvice = {
        name     = 'Coquette Vice',
        brand    = 'Invetero',
        model    = 'coqvice',
        price    = 238000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `coqvice`,
    },
    esperanto = {
        name     = 'Esperanto',
        brand    = 'Albany',
        model    = 'esperanto',
        price    = 252000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `esperanto`,
    },
    gauntletstx = {
        name     = 'Gauntlet STX',
        brand    = 'Bravado',
        model    = 'gauntletstx',
        price    = 268000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `gauntletstx`,
    },
    domellie = {
        name     = 'Dom Ellie',
        brand    = 'Vapid',
        model    = 'domellie',
        price    = 282000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `domellie`,
    },
    tfdominator = {
        name     = 'TF Dominator',
        brand    = 'Vapid',
        model    = 'tfdominator',
        price    = 295000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `tfdominator`,
    },
    buffalosl = {
        name     = 'Buffalo SL',
        brand    = 'Bravado',
        model    = 'buffalosl',
        price    = 308000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `buffalosl`,
    },
    niner = {
        name     = 'Niner',
        brand    = 'Obey',
        model    = 'niner',
        price    = 322000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `niner`,
    },
    zr = {
        name     = 'ZR',
        brand    = 'Annis',
        model    = 'zr',
        price    = 335000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `zr`,
    },
    dom645 = {
        name     = 'Dom 645',
        brand    = 'Vapid',
        model    = 'dom645',
        price    = 348000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `dom645`,
    },
    tulip2s = {
        name     = 'Tulip 2 S',
        brand    = 'Declasse',
        model    = 'tulip2s',
        price    = 362000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `tulip2s`,
    },
    eurosx32wb = {
        name     = 'Euros X32 WB',
        brand    = 'Annis',
        model    = 'eurosx32wb',
        price    = 375000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `eurosx32wb`,
    },
    vigeronew = {
        name     = 'Vigero New',
        brand    = 'Declasse',
        model    = 'vigeronew',
        price    = 388000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `vigeronew`,
    },
    stingersctulip2s = {
        name     = 'Stinger SC Tulip',
        brand    = 'Declasse',
        model    = 'stingersctulip2s',
        price    = 402000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `stingersctulip2s`,
    },
    raidenz = {
        name     = 'Raiden Z',
        brand    = 'Coil',
        model    = 'raidenz',
        price    = 418000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `raidenz`,
    },
    tempestas = {
        name     = 'Tempestas',
        brand    = 'Pegassi',
        model    = 'tempestas',
        price    = 432000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `tempestas`,
    },
    audace = {
        name     = 'Audace',
        brand    = 'Grotti',
        model    = 'audace',
        price    = 445000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `audace`,
    },
    turismocs = {
        name     = 'Turismo CS',
        brand    = 'Grotti',
        model    = 'turismocs',
        price    = 458000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `turismocs`,
    },
    elegyx = {
        name     = 'Elegy X',
        brand    = 'Annis',
        model    = 'elegyx',
        price    = 472000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `elegyx`,
    },
    remustwo = {
        name     = 'Remus Two',
        brand    = 'Annis',
        model    = 'remustwo',
        price    = 485000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `remustwo`,
    },
    elegyrh6 = {
        name     = 'Elegy RH6',
        brand    = 'Annis',
        model    = 'elegyrh6',
        price    = 498000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `elegyrh6`,
    },
    elegyheritage = {
        name     = 'Elegy Heritage',
        brand    = 'Annis',
        model    = 'elegyheritage',
        price    = 512000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `elegyheritage`,
    },
    gstghell1 = {
        name     = 'GSTG Hell1',
        brand    = 'Bravado',
        model    = 'gstghell1',
        price    = 522000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `gstghell1`,
    },
    hellfirelastcall = {
        name     = 'Hellfire Lastcall',
        brand    = 'Bravado',
        model    = 'hellfirelastcall',
        price    = 530000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `hellfirelastcall`,
    },
    buffalo4h = {
        name     = 'Buffalo 4H',
        brand    = 'Bravado',
        model    = 'buffalo4h',
        price    = 535000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `buffalo4h`,
    },
    coquette4c = {
        name     = 'Coquette 4C',
        brand    = 'Invetero',
        model    = 'coquette4c',
        price    = 540000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `coquette4c`,
    },
    jugularest = {
        name     = 'Jugular EST',
        brand    = 'Ocelot',
        model    = 'jugularest',
        price    = 545000,
        category = 'muscle',
        type     = 'automobile',
        hash     = `jugularest`,
    },

    -- ═══════════════════════════════════════════
    -- DRIFTCARS  (€285.000 – €720.000)
    -- ═══════════════════════════════════════════
    jesterwb = {
        name     = 'Jester WB',
        brand    = 'Dinka',
        model    = 'jesterwb',
        price    = 285000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `jesterwb`,
    },
    zinxy = {
        name     = 'Zinxy',
        brand    = 'Annis',
        model    = 'zinxy',
        price    = 345000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `zinxy`,
    },
    sentinel_rts = {
        name     = 'Sentinel RTS',
        brand    = 'Übermacht',
        model    = 'sentinel_rts',
        price    = 405000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `sentinel_rts`,
    },
    r300w = {
        name     = 'R300 W',
        brand    = 'Annis',
        model    = 'r300w',
        price    = 462000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `r300w`,
    },
    coquettewb = {
        name     = 'Coquette WB',
        brand    = 'Invetero',
        model    = 'coquettewb',
        price    = 518000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `coquettewb`,
    },
    jester3c = {
        name     = 'Jester 3 C',
        brand    = 'Dinka',
        model    = 'jester3c',
        price    = 572000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `jester3c`,
    },
    elegyz2 = {
        name     = 'Elegy Z2',
        brand    = 'Annis',
        model    = 'elegyz2',
        price    = 625000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `elegyz2`,
    },
    gp1wb = {
        name     = 'GP1 WB',
        brand    = 'Progen',
        model    = 'gp1wb',
        price    = 675000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `gp1wb`,
    },
    comet6scw = {
        name     = 'Comet 6 SCW',
        brand    = 'Pfister',
        model    = 'comet6scw',
        price    = 720000,
        category = 'sportsclassics',
        type     = 'automobile',
        hash     = `comet6scw`,
    },

    -- ═══════════════════════════════════════════
    -- SPORTS  (€420.000 – €1.150.000)
    -- ═══════════════════════════════════════════
    hycrh7 = {
        name     = 'HYC RH7',
        brand    = 'Annis',
        model    = 'hycrh7',
        price    = 420000,
        category = 'sports',
        type     = 'automobile',
        hash     = `hycrh7`,
    },
    zr390 = {
        name     = 'ZR 390',
        brand    = 'Annis',
        model    = 'zr390',
        price    = 498000,
        category = 'sports',
        type     = 'automobile',
        hash     = `zr390`,
    },
    estancia = {
        name     = 'Estancia',
        brand    = 'Grotti',
        model    = 'estancia',
        price    = 575000,
        category = 'sports',
        type     = 'automobile',
        hash     = `estancia`,
    },
    argento = {
        name     = 'Argento',
        brand    = 'Grotti',
        model    = 'argento',
        price    = 652000,
        category = 'sports',
        type     = 'automobile',
        hash     = `argento`,
    },
    turismorr = {
        name     = 'Turismo RR',
        brand    = 'Grotti',
        model    = 'turismorr',
        price    = 728000,
        category = 'sports',
        type     = 'automobile',
        hash     = `turismorr`,
    },
    infernussr = {
        name     = 'Infernus SR',
        brand    = 'Pegassi',
        model    = 'infernussr',
        price    = 808000,
        category = 'sports',
        type     = 'automobile',
        hash     = `infernussr`,
    },
    schlagenstr = {
        name     = 'Schlagen STR',
        brand    = 'Benefactor',
        model    = 'schlagenstr',
        price    = 888000,
        category = 'sports',
        type     = 'automobile',
        hash     = `schlagenstr`,
    },
    schafter3rs = {
        name     = 'Schafter 3 RS',
        brand    = 'Benefactor',
        model    = 'schafter3rs',
        price    = 968000,
        category = 'sports',
        type     = 'automobile',
        hash     = `schafter3rs`,
    },
    vesper = {
        name     = 'Vesper',
        brand    = 'Dewbauchee',
        model    = 'vesper',
        price    = 1050000,
        category = 'sports',
        type     = 'automobile',
        hash     = `vesper`,
    },
    cypherct = {
        name     = 'Cypher CT',
        brand    = 'Übermacht',
        model    = 'cypherct',
        price    = 1150000,
        category = 'sports',
        type     = 'automobile',
        hash     = `cypherct`,
    },

    -- ═══════════════════════════════════════════
    -- LUXURY  (€1.350.000 – €3.500.000)
    -- Echte statussymbolen – tientallen uren grinden
    -- Infernus WB = absolute top van de server
    -- ═══════════════════════════════════════════
    thirdteen = {
        name     = 'Thirdteen',
        brand    = 'Truffade',
        model    = 'thirdteen',
        price    = 1350000,
        category = 'super',
        type     = 'automobile',
        hash     = `thirdteen`,
    },
    expression = {
        name     = 'Expression',
        brand    = 'Enus',
        model    = 'expression',
        price    = 1550000,
        category = 'super',
        type     = 'automobile',
        hash     = `expression`,
    },
    osirisr = {
        name     = 'Osiris R',
        brand    = 'Pegassi',
        model    = 'osirisr',
        price    = 1780000,
        category = 'super',
        type     = 'automobile',
        hash     = `osirisr`,
    },
    toreroxoc = {
        name     = 'Torerox OC',
        brand    = 'Pegassi',
        model    = 'toreroxoc',
        price    = 2050000,
        category = 'super',
        type     = 'automobile',
        hash     = `toreroxoc`,
    },
    deimos = {
        name     = 'Deimos',
        brand    = 'Pegassi',
        model    = 'deimos',
        price    = 2320000,
        category = 'super',
        type     = 'automobile',
        hash     = `deimos`,
    },
    sheavas = {
        name     = 'Sheavas',
        brand    = 'Emperor',
        model    = 'sheavas',
        price    = 2580000,
        category = 'super',
        type     = 'automobile',
        hash     = `sheavas`,
    },
    sc_infernusx = {
        name     = 'SC Infernus X',
        brand    = 'Pegassi',
        model    = 'sc_infernusx',
        price    = 2850000,
        category = 'super',
        type     = 'automobile',
        hash     = `sc_infernusx`,
    },
    superd3 = {
        name     = 'Super D3',
        brand    = 'Enus',
        model    = 'superd3',
        price    = 3100000,
        category = 'super',
        type     = 'automobile',
        hash     = `superd3`,
    },
    elytron = {
        name     = 'Elytron',
        brand    = 'Överflöd',
        model    = 'elytron',
        price    = 3250000,
        category = 'super',
        type     = 'automobile',
        hash     = `elytron`,
    },
    tempestaes = {
        name     = 'Tempesta ES',
        brand    = 'Pegassi',
        model    = 'tempestaes',
        price    = 3350000,
        category = 'super',
        type     = 'automobile',
        hash     = `tempestaes`,
    },
    kriegerty2 = {
        name     = 'Krieger TY2',
        brand    = 'Benefactor',
        model    = 'kriegerty2',
        price    = 3420000,
        category = 'super',
        type     = 'automobile',
        hash     = `kriegerty2`,
    },
    fmjb = {
        name     = 'FMJ B',
        brand    = 'Vapid',
        model    = 'fmjb',
        price    = 3460000,
        category = 'super',
        type     = 'automobile',
        hash     = `fmjb`,
    },
    infernuswb = {
        name     = 'Infernus WB',
        brand    = 'Pegassi',
        model    = 'infernuswb',
        price    = 3500000,
        category = 'super',
        type     = 'automobile',
        hash     = `infernuswb`,
    },
}