-- 
-- Just loads of data that you want need/want to tweak
-- You don't need to change anything here, unless you really want to
-- 

Config.SpeedLimits = {
  ["Abattoir Ave"] = 60,
  ["Abe Milton Pkwy"] = 60,
  ["Ace Jones Dr"] = 60,
  ["Adam's Apple Blvd"] = 70,
  ["Aguja St"] = 50,
  ["Algonquin Blvd"] = 60,
  ["Alhambra Dr"] = 60,
  ["Alta Pl"] = 55,
  ["Alta St"] = 70,
  ["Amarillo Vista"] = 50,
  ["Amarillo Way"] = 60,
  ["Americano Way"] = 50,
  ["Armadillo Ave"] = 60,
  ["Atlee St"] = 55,
  ["Autopia Pkwy"] = 60,
  ["Banham Canyon Dr"] = 70,
  ["Barbareno Rd"] = 55,
  ["Bay City Ave"] = 55,
  ["Bay City Incline"] = 70,
  ["Baytree Canyon Rd"] = 70,
  ["Boulevard Del Perro"] = 60,
  ["Bridge St"] = 60,
  ["Brouge Ave"] = 55,
  ["Buccaneer Way"] = 75,
  ["Buen Vino Rd"] = 70,
  ["Caesars Place"] = 50,
  ["Calafia Rd"] = 55,
  ["Calais Ave"] = 60,
  ["Capital Blvd"] = 55,
  ["Carcer Way"] = 70,
  ["Carson Ave"] = 60,
  ["Cascabel Ave"] = 55,
  ["Cassidy Trail"] = 50,
  ["Cat-Claw Ave"] = 60,
  ["Catfish View"] = 60,
  ["Cavalry Blvd"] = 60,
  ["Chianski Passage"] = 55,
  ["Cholla Rd"] = 60,
  ["Cholla Springs Ave"] = 60,
  ["Chum St"] = 70,
  ["Chupacabra St"] = 55,
  ["Clinton Ave"] = 60,
  ["Cockingend Dr"] = 60,
  ["Conquistador St"] = 50,
  ["Cortes St"] = 50,
  ["Cougar Ave"] = 55,
  ["Covenant Ave"] = 55,
  ["Cox Way"] = 60,
  ["Crusade Rd"] = 55,
  ["Davis Ave"] = 70,
  ["Decker St"] = 60,
  ["Del Perro Fwy"] = 130,
  ["Didion Dr"] = 60,
  ["Dorset Dr"] = 70,
  ["Duluoz Ave"] = 60,
  ["Dunstable Dr"] = 60,
  ["Dunstable Ln"] = 60,
  ["Dutch London St"] = 70,
  ["East Eclipse Blvd"] = 60,
  ["East Galileo Ave"] = 60,
  ["East Joshua Road"] = 80,
  ["East Mirror Dr"] = 60,
  ["Eastbourne Way"] = 55,
  ["Edwood Way"] = 50,
  ["El Burro Blvd"] = 60,
  ["El Rancho Blvd"] = 70,
  ["Elgin Ave"] = 70,
  ["Elysian Fields Fwy"] = 80,
  ["Equality Way"] = 55,
  ["Exceptionalists Way"] = 60,
  ["Fenwell Pl"] = 60,
  ["Fort Zancudo Approach Rd"] = 50,
  ["Forum Dr"] = 60,
  ["Fudge Ln"] = 50,
  ["Galileo Park"] = 60,
  ["Galileo Rd"] = 70,
  ["Gentry Lane"] = 55,
  ["Ginger St"] = 55,
  ["Glory Way"] = 60,
  ["Goma St"] = 50,
  ["Grapeseed Ave"] = 60,
  ["Grapeseed Main St"] = 60,
  ["Great Ocean Hwy"] = 130,
  ["Greenwich Pkwy"] = 60,
  ["Greenwich Pl"] = 60,
  ["Greenwich Way"] = 60,
  ["Grove St"] = 55,
  ["Hangman Ave"] = 60,
  ["Hanger Way"] = 55,
  ["Hardy Way"] = 60,
  ["Hawick Ave"] = 60,
  ["Heritage Way"] = 60,
  ["Hillcrest Ave"] = 60,
  ["Hillcrest Ridge Access Rd"] = 60,
  ["Imagination Ct"] = 50,
  ["Ineseno Road"] = 55,
  ["Innocence Blvd"] = 70,
  ["Integrity Way"] = 55,
  ["Invention Ct"] = 50,
  ["Jamestown St"] = 55,
  ["Joad Ln"] = 60,
  ["Joshua Rd"] = 80,
  ["Kimble Hill Dr"] = 60,
  ["Kortz Dr"] = 55,
  ["Labor Pl"] = 60,
  ["Lake Vinewood Dr"] = 60,
  ["Lake Vinewood Est"] = 60,
  ["La Puerta Fwy"] = 130,
  ["Laguna Pl"] = 55,
  ["Las Lagunas Blvd"] = 70,
  ["Lesbos Ln"] = 60,
  ["Liberty St"] = 55,
  ["Lindsay Circus"] = 55,
  ["Little Bighorn Ave"] = 60,
  ["Lolita Ave"] = 60,
  ["Los Santos Freeway"] = 130,
  ["Low Power St"] = 60,
  ["Macdonald St"] = 60,
  ["Mad Wayne Thunder Dr"] = 60,
  ["Magellan Ave"] = 50,
  ["Limited Teststraat"] = 80,
  ["Marina Dr"] = 60,
  ["Marlowe Dr"] = 70,
  ["Melanoma St"] = 50,
  ["Meringue Ln"] = 60,
  ["Meteor St"] = 55,
  ["Milton Rd"] = 60,
  ["Mirror Park Blvd"] = 60,
  ["Mirror Pl"] = 60,
  ["Miriam Turner Overpass"] = 55,
  ["Morningwood Blvd"] = 60,
  ["Mountain View Dr"] = 60,
  ["Movie Star Way"] = 60,
  ["Mt Haan Rd"] = 70,
  ["Mt Vinewood Dr"] = 70,
  ["Mutiny Rd"] = 60,
  ["New Empire Way"] = 55,
  ["Nikola Ave"] = 60,
  ["Nikola Pl"] = 50,
  ["Niland Ave"] = 60,
  ["North Calafia Way"] = 55,
  ["North Conker Ave"] = 60,
  ["North Rockford Dr"] = 60,
  ["North Sheldon Ave"] = 60,
  ["Nowhere Rd"] = 50,
  ["O'Neil Way"] = 50,
  ["Occupation Ave"] = 60,
  ["Olympic Fwy"] = 130,
  ["Orchardville Ave"] = 55,
  ["Paleto Blvd"] = 60,
  ["Palomino Ave"] = 60,
  ["Palomino Fwy"] = 130,
  ["Panorama Dr"] = 70,
  ["Perth St"] = 50,
  ["Picture Perfect Drive"] = 60,
  ["Plaice Pl"] = 55,
  ["Playa Vista"] = 55,
  ["Popular St"] = 70,
  ["Portola Dr"] = 55,
  ["Power St"] = 70,
  ["Procopio Dr"] = 60,
  ["Procopio Promenade"] = 50,
  ["Prosperity St"] = 55,
  ["Pyrite Ave"] = 55,
  ["Red Desert Ave"] = 55,
  ["Richman St"] = 60,
  ["Rockford Dr"] = 60,
  ["Route 68"] = 80,
  ["Route 68 Approach"] = 80,
  ["Roy Lowenstein Blvd"] = 60,
  ["Rub St"] = 50,
  ["Sam Austin Dr"] = 50,
  ["San Andreas Ave"] = 70,
  ["San Vitus Blvd"] = 70,
  ["Sandcastle Way"] = 55,
  ["Seaview Rd"] = 60,
  ["Senora Fwy"] = 130,
  ["Senora Rd"] = 70,
  ["Senora Way"] = 70,
  ["Shank St"] = 50,
  ["Signal St"] = 55,
  ["Sinners Passage"] = 55,
  ["Sinner St"] = 55,
  ["Smoke Tree Rd"] = 60,
  ["South Arsenal St"] = 60,
  ["South Boulevard Del Perro"] = 60,
  ["South Mo Milton Dr"] = 60,
  ["South Rockford Dr"] = 60,
  ["South Shambles St"] = 55,
  ["Spanish Ave"] = 55,
  ["Strangeways Dr"] = 55,
  ["Strawberry Ave"] = 70,
  ["Supply St"] = 55,
  ["Sustancia Rd"] = 75,
  ["Swiss St"] = 55,
  ["Tackle St"] = 50,
  ["Tongva Dr"] = 70,
  ["Tower Way"] = 60,
  ["Tug St"] = 50,
  ["Union Rd"] = 70,
  ["Utopia Gardens"] = 50,
  ["Vespucci Blvd"] = 70,
  ["Vinewood Blvd"] = 70,
  ["Vinewood Park Dr"] = 60,
  ["Vitus St"] = 50,
  ["Voodoo Place"] = 55,
  ["West Eclipse Blvd"] = 60,
  ["West Galileo Ave"] = 60,
  ["West Mirror Drive"] = 60,
  ["Wild Oats Dr"] = 60,
  ["Whispymound Dr"] = 50,
  ["Zancudo Ave"] = 60,
  ["Zancudo Barranca"] = 70,
  ["Zancudo Grande Valley"] = 70,
  ["Zancudo Rd"] = 60
}

-- NOTE: This may already have been done in your framework: to avoid an unncessary thread
-- you can set this to false, delete it comment it out, whatever is easier for you :)
Config.HideBaseGameHudComponents = {
  1, -- WANTED_STARS,
  2, -- WEAPON_ICON
  3, -- CASH
  4, -- MP_CASH
  5, -- MP_MESSAGE
  6, -- VEHICLE_NAME
  7, -- AREA_NAME
  8, -- VEHICLE_CLASS
  9, -- STREET_NAME
  -- 10, --HELP_TEXT
  -- 11, --FLOATING_HELP_TEXT_1
  -- 12, --FLOATING_HELP_TEXT_2
  13, --CASH_CHANGE
  -- 14, --RETICLE
  -- 15, --SUBTITLE_TEXT
  -- 16, --RADIO_STATIONS
  -- 17, --SAVING_GAME,
  -- 18, --GAME_STREAM
  -- 19, --WEAPON_WHEEL
  -- 20, --WEAPON_WHEEL_STATS
  -- 21, --HUD_COMPONENTS
  -- 22, --HUD_WEAPONS
}

-- Use custom street or zone names
-- Tutorial: https://docs.jgscripts.com/hud/custom-street-zone-names
Config.CustomStreetNames = {
  -- [0xF5BF6BDD] = "Runway",
}
Config.CustomZoneNames = {
  -- AIRP = "Los Santos International Airport",
}
Config.CustomNamesShouldUpdateGameTextEntries = false

Config.WeaponNames = {
  WEAPON_KNIFE = "Knife",
  WEAPON_NIGHTSTICK = "Nightstick",
  WEAPON_HAMMER = "Hammer",
  WEAPON_BAT = "Baseball Bat",
  WEAPON_GOLFCLUB = "Golf Club",
  WEAPON_CROWBAR = "Crowbar",
  WEAPON_PISTOL = "Pistol",
  WEAPON_COMBATPISTOL = "Combat Pistol",
  WEAPON_APPISTOL = "AP Pistol",
  WEAPON_PISTOL50 = "Pistol .50",
  WEAPON_MICROSMG = "Micro SMG",
  WEAPON_SMG = "SMG",
  WEAPON_ASSAULTSMG = "Assault SMG",
  WEAPON_ASSAULTRIFLE = "Assault Rifle",
  WEAPON_CARBINERIFLE = "Carbine Rifle",
  WEAPON_ADVANCEDRIFLE = "Advanced Rifle",
  WEAPON_MG = "MG",
  WEAPON_COMBATMG = "Combat MG",
  WEAPON_PUMPSHOTGUN = "Pump Shotgun",
  WEAPON_SAWNOFFSHOTGUN = "Sawed-Off Shotgun",
  WEAPON_ASSAULTSHOTGUN = "Assault Shotgun",
  WEAPON_BULLPUPSHOTGUN = "Bullpup Shotgun",
  WEAPON_STUNGUN = "Stun Gun",
  WEAPON_SNIPERRIFLE = "Sniper Rifle",
  WEAPON_HEAVYSNIPER = "Heavy Sniper",
  WEAPON_GRENADELAUNCHER = "Grenade Launcher",
  WEAPON_RPG = "RPG",
  WEAPON_MINIGUN = "Minigun",
  WEAPON_GRENADE = "Grenade",
  WEAPON_STICKYBOMB = "Sticky Bomb",
  WEAPON_SMOKEGRENADE = "Smoke Grenade",
  WEAPON_BZGAS = "BZ Gas",
  WEAPON_MOLOTOV = "Molotov",
  WEAPON_FIREEXTINGUISHER = "Fire Extinguisher",
  WEAPON_PETROLCAN = "Petrol Can",
  WEAPON_BALL = "Ball",
  WEAPON_FLARE = "Flare",
  WEAPON_SNOWBALL = "Snowball",
  WEAPON_FLAREGUN = "Flare Gun",
  WEAPON_GARBAGEBAG = "Garbage Bag",
  WEAPON_HANDCUFFS = "Handcuffs",
  WEAPON_BATTLEAXE = "Battle Axe",
  WEAPON_COMPACTLAUNCHER = "Compact Grenade Launcher",
  WEAPON_MINISMG = "Mini SMG",
  WEAPON_PIPEBOMB = "Pipe Bomb",
  WEAPON_POOLCUE = "Pool Cue",
  WEAPON_WRENCH = "Wrench",
  WEAPON_FLASHLIGHT = "Flashlight",
  WEAPON_DAGGER = "Antique Cavalry Dagger",
  WEAPON_VINTAGEPISTOL = "Vintage Pistol",
  WEAPON_MUSKET = "Musket",
  WEAPON_FIREWORK = "Firework Launcher",
  WEAPON_MARKSMANRIFLE = "Marksman Rifle",
  WEAPON_HEAVYSHOTGUN = "Heavy Shotgun",
  WEAPON_PROXMINE = "Proximity Mine",
  WEAPON_HOMINGLAUNCHER = "Homing Launcher",
  WEAPON_COMPACTRIFLE = "Compact Rifle",
  WEAPON_MACHINEPISTOL = "Machine Pistol",
  WEAPON_SWITCHBLADE = "Switchblade",
  WEAPON_REVOLVER = "Heavy Revolver",
  WEAPON_DOUBLEACTION = "Double-Action Revolver",
  WEAPON_MARKSMANPISTOL = "Marksman Pistol",
  WEAPON_RAYPISTOL = "Up-n-Atomizer",
  WEAPON_RAYCARBINE = "Unholy Hellbringer",
  WEAPON_RAYMINIGUN = "Widowmaker",
  WEAPON_NAVYREVOLVER = "Navy Revolver",
  WEAPON_CERAMICPISTOL = "Ceramic Pistol",
  WEAPON_STONE_HATCHET = "Stone Hatchet",
  WEAPON_PIPEWRENCH = "Pipe Wrench",
  WEAPON_PISTOL_MK2 = "Pistol Mk II",
  WEAPON_SNSPISTOL_MK2 = "SNS Pistol Mk II",
  WEAPON_REVOLVER_MK2 = "Heavy Revolver Mk II",
  WEAPON_SMG_MK2 = "SMG Mk II",
  WEAPON_PUMPSHOTGUN_MK2 = "Pump Shotgun Mk II",
  WEAPON_SPECIALCARBINE_MK2 = "Special Carbine Mk II",
  WEAPON_BULLPUPRIFLE_MK2 = "Bullpup Rifle Mk II",
  WEAPON_COMBATMG_MK2 = "Combat MG Mk II",
  WEAPON_HEAVYSNIPER_MK2 = "Heavy Sniper Mk II",
  WEAPON_ASSAULTRIFLE_MK2 = "Assault Rifle Mk II",
  WEAPON_CARBINERIFLE_MK2 = "Carbine Rifle Mk II",
  WEAPON_MILITARYRIFLE = "Military Rifle",
  WEAPON_COMBATSHOTGUN = "Combat Shotgun",
  WEAPON_GADGETPISTOL = "Perico Pistol",
  WEAPON_EMPLAUNCHER = "Compact EMP Launcher",
  WEAPON_HEAVYRIFLE = "Heavy Rifle",
  WEAPON_PRECISIONRIFLE = "Precision Rifle",
  WEAPON_TACTICALRIFLE = "Service Carbine"
}

Config.TrainMetroStations = {
  [1] = { name = "LSIA Terminal 4", coords = vec(-1083.3578, -2716.4917, -7.4101), nextStation = { Northbound = { h = 316, s = 2 }, Southbound = { h = 137, s = false } } },
  [2] = { name = "LSIA Parking", coords = vec(-873.6451, -2313.1482, -12.6264), nextStation = { Northbound = { h = 333, s = 3 }, Southbound = { h = 151, s = 1 } } },
  [3] = { name = "Puerto Del Sol", coords = vec(-538.3027, -1289.2268, 25.9013), nextStation = { Northbound = { h = 333, s = 4 }, Southbound = { h = 151, s = 2 } } },
  [4] = { name = "Strawberry", coords = vec(260.8647, -1210.0208, 38.0746), nextStation = { Northbound = { h = 267, s = 6 }, Southbound = { h = 86, s = 3 } } },
  -- [5] = { name = "Pillbox North (Under Construction)", coords = vec(140.9126, -599.2263, 17.7564), nextStation = { { h = 64, s = 6 }, { h = 258, s = 4 } } },
  [6] = { name = "Burton", coords = vec(-294.8436, -336.0311, 10.0631), nextStation = { Northbound = { h = 349, s = 7 }, Southbound = { h = 172, s = 4 } } },
  [7] = { name = "Portola Drive", coords = vec(-813.0384, -136.0313, 19.9503), nextStation = { Northbound = { h = 117, s = 8 }, Southbound = { h = 292, s = 6 } } },
  [8] = { name = "Del Perro", coords =  vec(-1350.6287, -467.3718, 15.0454), nextStation = { Northbound = { h = 208, s = 9 }, Southbound = { h = 28, s = 7 } } },
  [9] = { name = "Little Seoul", coords =  vec(-497.0356, -673.1466, 11.8090), nextStation = { Northbound = { h = 276, s = 10 }, Southbound = { h = 83, s = 8 } } },
  [10] = { name = "Pillbox South", coords = vec(-211.6538, -1028.5626, 30.5675), nextStation = { Northbound = { h = 151, s = 11 }, Southbound = { h = 335, s = 9 } } },
  [11] = { name = "Davis", coords =  vec(112.2249, -1723.0388, 30.5415), nextStation = { Northbound = { h = 230, s = false }, Southbound = { h = 45, s = 10 } } },
}

-- Add electric vehicles to disable combustion engine features
-----------------------------------------------------------------------
-- PLEASE NOTE: In b3258 (Bottom Dollar Bounties) and newer, electric
-- vehicles are detected automatically, so this list is not used! 
Config.ElectricVehicles = {
  "Airtug",     "buffalo5",   "caddy",
  "Caddy2",     "caddy3",     "coureur",
  "cyclone",    "cyclone2",   "imorgon",
  "inductor",   "iwagen",     "khamelion",
  "metrotrain", "minitank",   "neon",
  "omnisegt",   "powersurge", "raiden",
  "rcbandito",  "surge",      "tezeract",
  "virtue",     "vivanite",   "voltic",
  "voltic2",
}

---------------------------------------------
-- Register custom street/zone names globally
if Config.CustomNamesShouldUpdateGameTextEntries then
  for hash, val in pairs(Config.CustomStreetNames) do
    AddTextEntryByHash(hash, val)
  end

  for name, val in pairs(Config.CustomZoneNames) do
    AddTextEntryByHash(joaat(name), val)
  end
end