INSERT INTO `items` (`name`, `label`, `weight`) VALUES
	('blueprint_snspistol', 'Blueprint - SNS Pistol', 100),
	('blueprint_carbinerifle_mk2', 'Blueprint - Carbine Rifle MK2', 100),
	('burger_sprunk', 'Sprunk', 500),
	('blueprint_pistol50', 'Blueprint - Pistol .50', 100),
	('blueprint_heavysniper', 'Blueprint - Heavy Sniper', 100),
	('blueprint_assaultsmg', 'Blueprint - Assault SMG', 100),
	('blueprint_marksmanpistol', 'Blueprint - Marksman Pistol', 100),
	('blueprint_pumpshotgun_mk2', 'Blueprint - Pump Shotgun MK2', 100),
	('cheddar', 'Cheddar cheese', 20),
	('blueprint_marksmanrifle', 'Blueprint - Marksman Rifle', 100),
	('red_grapes', 'Red grapes', 200),
	('blueprint_heavysniper_mk2', 'Blueprint - Heavy Sniper MK2', 100),
	('zipties', 'Zipties', 20),
	('blueprint_assaultrifle_mk2', 'Blueprint - Assault Rifle MK2', 100),
	('blueprint_smg_mk2', 'Blueprint - SMG MK2', 100),
	('blueprint_pistol_mk2', 'Blueprint - Pistol MK2', 100),
	('blueprint_smg', 'Blueprint - SMG', 100),
	('grape_snips', 'Grape snips', 200),
	('burger_chickenwrap', 'Chicken wrap', 200),
	('white_wine', 'White wine', 1200),
	('burger_emptycup', 'Empty cup', 50),
	('blueprint_tecpistol', 'Blueprint - Tec Pistol', 100),
	('baguette', 'Baguette', 50),
	('blueprint_bullpuprifle', 'Blueprint - Bullpup Rifle', 100),
	('empty_bottle', 'Empty wine bottle', 200),
	('blueprint_advancedrifle', 'Blueprint - Advanced Rifle', 100),
	('blueprint_marksmanrifle_mk2', 'Blueprint - Marksman Rifle MK2', 100),
	('blueprint_precisionrifle', 'Blueprint - Precision Rifle', 100),
	('blueprint_gusenberg', 'Blueprint - Gusenberg', 100),
	('burger_coffee', 'Coffee', 250),
	('blueprint_specialcarbine', 'Blueprint - Special Carbine', 100),
	('blueprint_bullpuprifle_mk2', 'Blueprint - Bullpup Rifle MK2', 100),
	('sliced_potato', 'Potato', 200),
	('blueprint_combatpistol', 'Blueprint - Combat Pistol', 100),
	('blueprint_assaultrifle', 'Blueprint - Assault Rifle', 100),
	('blueprint_minismg', 'Blueprint - Mini SMG', 100),
	('blueprint_militaryrifle', 'Blueprint - Military Rifle', 100),
	('blueprint_combatmg_mk2', 'Blueprint - Combat MG MK2', 100),
	('blueprint_tacticalrifle', 'Blueprint - Tactical Rifle', 100),
	('red_wine_juice', 'Red wine juice', 1000),
	('blueprint_assaultshotgun', 'Blueprint - Assault Shotgun', 100),
	('red_wine', 'Red wine', 1200),
	('bun', 'Burger bun', 50),
	('tomato', 'Tomato', 50),
	('white_grapes', 'White grapes', 200),
	('blueprint_heavyrifle', 'Blueprint - Heavy Rifle', 100),
	('blueprint_combatmg', 'Blueprint - Combat MG', 100),
	('blueprint_carbinerifle', 'Blueprint - Carbine Rifle', 100),
	('sliced_onion', 'Sliced onion', 30),
	('patty', 'Patty', 150),
	('blueprint_compactrifle', 'Blueprint - Compact Rifle', 100),
	('burger_moneyshot', 'Money shot burger', 300),
	('cooked_patty', 'Cooked patty', 150),
	('chicken_strips', 'Chicken strips', 150),
	('blueprint_appistol', 'Blueprint - APPistol', 100),
	('handcuffs', 'Handcuffs', 200),
	('raw_chicken', 'Raw chicken', 150),
	('blueprint_mg', 'Blueprint - MG', 100),
	('wrap', 'Tortilla wrap', 50),
	('blueprint_bullpupshotgun', 'Blueprint - Bullpup Shotgun', 100),
	('bacon', 'Bacon', 50),
	('burger_ecola', 'eCola', 500),
	('blueprint_specialcarbine_mk2', 'Blueprint - Special Carbine MK2', 100),
	('blueprint_combatpdw', 'Blueprint - Combat PDW', 100),
	('burger_fries', 'Freedom fries', 200),
	('burger_applepie', 'Apple pie', 300),
	('blueprint_heavypistol', 'Blueprint - Heavy Pistol', 100),
	('burger_donut', 'Donut', 300),
	('burger_meatfree', 'Meat free burger', 200),
	('blueprint_revolver', 'Blueprint - Revolver', 100),
	('burger_torpedo', 'Torpedo Sandwich', 200),
	('burger_heartstopper', 'Heart stopper burger', 500),
	('burger_bleeder', 'Bleeder burger', 300),
	('blueprint_pumpshotgun', 'Blueprint - Pump Shotgun', 100),
	('blueprint_musket', 'Blueprint - Musket', 100),
	('blueprint_revolver_mk2', 'Blueprint - Revolver MK2', 100),
	('white_wine_juice', 'White wine juice', 1000),
	('blueprint_pistol', 'Blueprint - Pistol', 100),
	('blueprint_metaldetector', 'Blueprint - Metal Detector', 100),
	('blueprint_machinepistol', 'Blueprint - Machine Pistol', 100),
	('blueprint_heavyshotgun', 'Blueprint - Heavy Shotgun', 100),
	('lettuce', 'Fresh salad', 50),
	('blueprint_combatshotgun', 'Blueprint - Combat Shotgun', 100),
	('blueprint_digiscanner', 'Blueprint - Digiscanner', 100),
	('icetea', 'Icetea', 300),
	('lemonade', 'Lemonade', 300),
	('mojito', 'Mojito', 300),
	('martini', 'Martini', 300),
	('champagne', 'Champagne', 300),
	('vodka', 'Vodka', 300),
	('tequila', 'Tequila', 300),

;